16 feature 6 c message history system
CSC207-2022F-UofT/course-project-wanna-date pull request #24
Opened 2022-11-20 06:59 UTC by llukeham

Message History Entity

2022-11-20 21:44 UTC, supriyavasanth approved these changes
This looks good, but I'm not sure how I am supposed to access all the messages from their chat because it only stores the last message as a string. Or are you trying to create a new object for each message? I will try to work with this though for now.

2022-11-20 21:55 UTC, Adelineleonardi approved these changes
Nice work Luke. Good documentation and easy to read code, but this is only the get function, so don't forget to submit the implementation.

2022-11-21 12:12 UTC, GlassInterface requested changes
Hi Luke, just looking over the code - I agree that it's good so far, but also refer to the other team members' feedback. I would also suggest adding a JavaDoc comment to the MessageHistory since it does not appear entirely clear as to what is going on in it. For instance, is this the primary method from which the use case does its work?

EDIT: I accidentally selected the request for changes. I'll approve the changes so far, but just remember to consider the feedback the team has given!

2022-11-21 12:14 UTC, GlassInterface approved these changes

2022-11-21 12:16 UTC, merged